
package org.lukebillington.university.sharesbroker.services.CurrencyConversion;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CurrencyConversionWSService", targetNamespace = "http://DOCwebServices/", wsdlLocation = "http://localhost:9000/CurrencyConversionWS?wsdl")
public class CurrencyConversionWSService
    extends Service
{

    private final static URL CURRENCYCONVERSIONWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException CURRENCYCONVERSIONWSSERVICE_EXCEPTION;
    private final static QName CURRENCYCONVERSIONWSSERVICE_QNAME = new QName("http://DOCwebServices/", "CurrencyConversionWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9000/CurrencyConversionWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CURRENCYCONVERSIONWSSERVICE_WSDL_LOCATION = url;
        CURRENCYCONVERSIONWSSERVICE_EXCEPTION = e;
    }

    public CurrencyConversionWSService() {
        super(__getWsdlLocation(), CURRENCYCONVERSIONWSSERVICE_QNAME);
    }

    public CurrencyConversionWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CURRENCYCONVERSIONWSSERVICE_QNAME, features);
    }

    public CurrencyConversionWSService(URL wsdlLocation) {
        super(wsdlLocation, CURRENCYCONVERSIONWSSERVICE_QNAME);
    }

    public CurrencyConversionWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CURRENCYCONVERSIONWSSERVICE_QNAME, features);
    }

    public CurrencyConversionWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CurrencyConversionWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ICurrencyConversionWS
     */
    @WebEndpoint(name = "CurrencyConversionWSPort")
    public ICurrencyConversionWS getCurrencyConversionWSPort() {
        return super.getPort(new QName("http://DOCwebServices/", "CurrencyConversionWSPort"), ICurrencyConversionWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ICurrencyConversionWS
     */
    @WebEndpoint(name = "CurrencyConversionWSPort")
    public ICurrencyConversionWS getCurrencyConversionWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://DOCwebServices/", "CurrencyConversionWSPort"), ICurrencyConversionWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CURRENCYCONVERSIONWSSERVICE_EXCEPTION!= null) {
            throw CURRENCYCONVERSIONWSSERVICE_EXCEPTION;
        }
        return CURRENCYCONVERSIONWSSERVICE_WSDL_LOCATION;
    }

}
